# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd717a9226a0c711d8fc13fcfb509810bea35bdc9a823a37bd6109e6d912608fe2064e6b67af0e6fc025ae163f73834e2c569cca9fd589192f11c87c0a89b1ca

test:
  secret_key_base: 777acb5a7721dfb39c37998c4e87c57081384c3819a7cb06c27aa3131d065b2c6795a166ef933daf5f185693890efdf19ddd64ba58f021e470b0ea54a4dc2b0d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
